import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}

export const mockGames = [
  {
    id: "1",
    title: "本草奇缘",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "角色扮演",
    tags: ["中医", "国风", "收集"],
    source: "tcm" as const,
    rating: 4.8,
    players: 12500,
  },
  {
    id: "13",
    title: "草药消消乐",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "休闲",
    tags: ["三消", "中医", "药材", "益智"],
    source: "tcm" as const,
    rating: 4.6,
    players: 28600,
  },
  {
    id: "14",
    title: "五行宠物",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "休闲",
    tags: ["养成", "五行", "性格测试"],
    source: "tcm" as const,
    rating: 4.5,
    players: 18200,
  },
  {
    id: "15",
    title: "情绪岛",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "冒险",
    tags: ["情绪", "探索", "心理"],
    source: "tcm" as const,
    rating: 4.3,
    players: 15600,
  },
  {
    id: "16",
    title: "心力气球",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "休闲",
    tags: ["互动", "心理", "平衡"],
    source: "tcm" as const,
    rating: 4.2,
    players: 12800,
  },
  {
    id: "17",
    title: "元素塔防",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "策略",
    tags: ["塔防", "五行", "战略"],
    source: "tcm" as const,
    rating: 4.7,
    players: 22400,
  },
  {
    id: "18",
    title: "五行卡牌",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "卡牌",
    tags: ["收集", "五行", "闯关"],
    source: "tcm" as const,
    rating: 4.6,
    players: 19800,
  },
  {
    id: "19",
    title: "气血宠物",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "养成",
    tags: ["宠物", "习惯", "健康"],
    source: "tcm" as const,
    rating: 4.4,
    players: 16500,
  },
  {
    id: "2",
    title: "经络大师",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "策略",
    tags: ["中医", "益智", "教育"],
    source: "tcm" as const,
    rating: 4.5,
    players: 8300,
  },
  {
    id: "3",
    title: "五行消除",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "休闲",
    tags: ["三消", "轻松", "五行"],
    source: "h5" as const,
    rating: 4.2,
    players: 45000,
  },
  {
    id: "4",
    title: "针灸模拟器",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "模拟",
    tags: ["中医", "教育", "精准"],
    source: "tcm" as const,
    rating: 4.7,
    players: 6200,
  },
  {
    id: "5",
    title: "药王传说",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "角色扮演",
    tags: ["国风", "开放世界", "中医"],
    source: "opensource" as const,
    rating: 4.4,
    players: 15800,
  },
  {
    id: "6",
    title: "中医小镇",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "模拟经营",
    tags: ["经营", "建造", "中医"],
    source: "tcm" as const,
    rating: 4.6,
    players: 9700,
  },
  {
    id: "7",
    title: "飞针走灸",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "动作",
    tags: ["技巧", "中医", "反应"],
    source: "h5" as const,
    rating: 4.0,
    players: 32000,
  },
  {
    id: "8",
    title: "药材大战僵尸",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "塔防",
    tags: ["策略", "中医", "防御"],
    source: "opensource" as const,
    rating: 4.3,
    players: 18500,
  },
  {
    id: "9",
    title: "中医问诊",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "模拟",
    tags: ["角色", "对话", "中医"],
    source: "tcm" as const,
    rating: 4.5,
    players: 7200,
  },
  {
    id: "10",
    title: "穴位大冒险",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "冒险",
    tags: ["平台", "教育", "中医"],
    source: "h5" as const,
    rating: 4.1,
    players: 28000,
  },
  {
    id: "11",
    title: "中医卡牌",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "卡牌",
    tags: ["收集", "策略", "中医"],
    source: "opensource" as const,
    rating: 4.4,
    players: 14200,
  },
  {
    id: "12",
    title: "五行战记",
    thumbnail: "/placeholder.svg?height=200&width=350",
    category: "策略",
    tags: ["回合制", "五行", "中医"],
    source: "tcm" as const,
    rating: 4.7,
    players: 10500,
  },
]

